#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H

#define ADC_MAX_VALUE 4095
#define MOTOR_MAX_SPEED_RPM 3000.0f
#define CONTROL_SAMPLE_TIME_MS 10U
#define CONTROL_SAMPLE_TIME_SECONDS 0.01f
#define SIMULATION_DURATION_MS 11000U

#endif
